CREATE TABLE CovidVaccinations ( iso_code VARCHAR2(26),
  continent VARCHAR2(26),
  location VARCHAR2(26),
  collection_date DATE,
  total_tests NUMBER(38),
  new_tests NUMBER(38),
  total_tests_per_thousand NUMBER(38, 3),
  new_tests_per_thousand NUMBER(38, 3),
  new_tests_smoothed NUMBER(38, 3),
  new_tests_smoothed_per_thousand NUMBER(38, 3),
  positive_rate NUMBER(38, 4),
  tests_per_case NUMBER(38, 3),
  tests_units VARCHAR2(26),
  total_vaccinations NUMBER(38),
  people_vaccinated NUMBER(38),
  people_fully_vaccinated NUMBER(38),
  total_boosters NUMBER(38),
  new_vaccinations NUMBER(38),
  new_vaccinations_smoothed NUMBER(38),
  total_vaccinations_per_hundred NUMBER(38, 3),
  people_vaccinated_per_hundred NUMBER(38, 3),
  people_fully_vaccinated_per_hundred NUMBER(38, 3),
  total_boosters_per_hundred NUMBER(38, 3),
  new_vaccinations_smoothed_per_million NUMBER(38, 3),
  new_people_vaccinated_smoothed NUMBER(38),
  new_people_vaccinated_smoothed_per_hundred NUMBER(38, 4),
  stringency_index NUMBER(38, 3),
  population_density NUMBER(38, 3),
  median_age NUMBER(38, 1),
  aged_65_older NUMBER(38, 3),
  aged_70_older NUMBER(38, 3),
  gdp_per_capita NUMBER(38, 3),
  extreme_poverty NUMBER(38, 3),
  cardiovasc_death_rate NUMBER(38, 3),
  diabetes_prevalence NUMBER(38, 3),
  female_smokers NUMBER(38, 3),
  male_smokers NUMBER(38, 3),
  handwashing_facilities NUMBER(38, 3),
  hospital_beds_per_thousand NUMBER(38, 3),
  life_expectancy NUMBER(38, 3),
  human_development_index NUMBER(38, 3),
  excess_mortality_cumulative_absolute NUMBER(38, 5),
  excess_mortality_cumulative NUMBER(38, 5),
  excess_mortality NUMBER(38, 5),
  excess_mortality_cumulative_per_million NUMBER(38, 5)) ;
 
select * from covidvaccinations where rownum <= 20;
  